version: '3.2'
services:
    react:
        container_name: trubbi-react
        image: node:16.14.2-slim
        user: node
        working_dir: /var/www/html
        command: bash -c "npm install && npm run start"
        volumes:
            - ./:/var/www/html/
        ports:
            - "3000:3000"
        networks:
            - trubbi-net

networks:
  trubbi-net:
